## Acheivement 6.1 - Cleaning dataset

In [95]:
# import libraries
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [96]:
path=r'C:\Users\chloe\Documents\Documents\Documents\Career Foundry\Data Immersion'

In [97]:
countyHealthFactors = pd.read_csv(os.path.join(path, 'Achievement 6', '6.1_Sourcing Dataset_deBeus.csv'), index_col = 0)

In [98]:
countyHealthFactors.head()

,County,# Alcohol-Impaired Driving Deaths,% Driving Deaths with Alcohol Involvement,Severe Housing Problems,Severe Housing Cost Burden,Overcrowding,Inadequate Facilities,% Drive Alone to Work,Households with Broadband Access,% Households with Broadband Access
State,,,,,,,,,,
Alabama,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alabama,Autauga,18.0,32.1,14.4,12.6,1.1,1.6,86.4,18679.0,85.5
Alabama,Baldwin,57.0,32.2,12.2,10.6,1.3,0.6,81.4,76602.0,87.9
Alabama,Barbour,12.0,37.5,16.2,13.5,3.9,0.6,83.1,5872.0,64.6
Alabama,Bibb,6.0,21.4,11.3,8.0,1.2,2.2,87.0,5284.0,74.6

In [99]:
#Size Criteria
countyHealthFactors.shape
#3195 columns - contains at least 1,500
#82 rows

(3194, 10)

In [100]:
#Geographic Criteria
countyHealthFactors[['County']]

              County
State
Alabama      Alabama
Alabama      Autauga
Alabama      Baldwin
Alabama      Barbour
Alabama         Bibb
...              ...
Wyoming        Teton
Wyoming        Uinta
Wyoming     Washakie
Wyoming       Weston
NaN      Grand Total

[3194 rows x 1 columns]

In [101]:
countyHealthFactors.columns

Index(['County', '# Alcohol-Impaired Driving Deaths',
       '% Driving Deaths with Alcohol Involvement', 'Severe Housing Problems',
       'Severe Housing Cost Burden', 'Overcrowding', 'Inadequate Facilities',
       '% Drive Alone to Work', 'Households with Broadband Access',
       '% Households with Broadband Access'],
      dtype='object')

In [102]:
countyHealthFactors = countyHealthFactors.rename(columns={'# Alcohol-Impaired Driving Deaths': 'alcoholInvolvementDrivingDeaths', '% Driving Deaths with Alcohol Involvement': 'alcoholInvolvementDrivingDeathsRate', '% Drive Alone to Work': 'driveAloneToWorkRate', '% Households with Broadband Access': 'householdsWithBroadbandAccessRate', 'Households with Broadband Access':'householdsWithBroadbandAccess', 'Severe Housing Problems':'severeHousingProblemsRate', 'Severe Housing Cost Burden':'housingCostBurdenRate', 'Overcrowding':'housingOvercrowdingRate', 'Inadequate dFacilities':'housingInadequateFacilities Rate'})
#rename columns

In [103]:
countyHealthFactors.columns

Index(['County', 'alcoholInvolvementDrivingDeaths',
       'alcoholInvolvementDrivingDeathsRate', 'severeHousingProblemsRate',
       'housingCostBurdenRate', 'housingOvercrowdingRate',
       'Inadequate Facilities', 'driveAloneToWorkRate',
       'householdsWithBroadbandAccess', 'householdsWithBroadbandAccessRate'],
      dtype='object')

In [104]:
#3 or more continuous variables
countyHealthFactors[['severeHousingProblemsRate','householdsWithBroadbandAccessRate','alcoholInvolvementDrivingDeathsRate']]

,severeHousingProblemsRate,householdsWithBroadbandAccessRate,alcoholInvolvementDrivingDeathsRate
State,,,
Alabama,NaN,NaN,NaN
Alabama,14.400000,85.500000,32.100000
Alabama,12.200000,87.900000,32.200000
Alabama,16.200000,64.600000,37.500000
Alabama,11.300000,74.600000,21.400000
...,...,...,...
Wyoming,15.410200,90.462701,18.181818
Wyoming,8.689928,90.644951,17.391304
Wyoming,7.280832,85.430267,0.000000
Wyoming,12.283737,81.299927,22.222222
NaN,13.051312,80.541481,27.485404

### Now let's create some categorical variables based on rates

In [105]:
countyHealthFactors.describe()

,alcoholInvolvementDrivingDeaths,alcoholInvolvementDrivingDeathsRate,severeHousingProblemsRate,housingCostBurdenRate,housingOvercrowdingRate,Inadequate Facilities,driveAloneToWorkRate,householdsWithBroadbandAccess,householdsWithBroadbandAccessRate
count,3116.000000,3116.000000,3143.000000,3143.000000,3143.000000,3143.000000,3143.000000,3.143000e+03,3143.000000
mean,31.827343,27.485409,13.051223,20.367270,4.834478,2.450829,78.570105,6.865442e+04,80.541443
std,888.772359,15.149048,4.365535,570.748694,135.496935,68.694952,7.647947,1.926826e+06,7.887127
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.835840,2.500000e+01,37.037037
25%,3.000000,18.333333,10.400000,7.949405,1.241508,0.629931,76.072439,3.146500e+03,76.427194
50%,7.000000,26.562500,12.576985,9.796910,1.880878,0.956768,79.815668,7.914000e+03,81.689511
75%,15.000000,34.210526,14.940690,12.041899,2.871666,1.447858,83.016003,2.186200e+04,85.895646
max,49587.000000,100.000000,67.826087,32007.213630,7597.540339,3851.348901,98.437500,1.078904e+08,97.590361

In [106]:
#let's create categories based on national median (since housing burden mean is high because of an outlier)
countyHealthFactors['alcoholInvolvementDrivingDeathsRate'].value_counts(dropna = False)

0.000000     153
33.333333    140
25.000000    103
50.000000     87
NaN           78
            ...
12.765957      1
25.454545      1
16.233766      1
15.841584      1
27.485404      1
Name: alcoholInvolvementDrivingDeathsRate, Length: 867, dtype: int64

In [107]:
countyHealthFactors.loc[countyHealthFactors['alcoholInvolvementDrivingDeathsRate'] == 0.00, 'alcoholDrivingDeathsRateCategory'] = 0
countyHealthFactors.loc[(countyHealthFactors['alcoholInvolvementDrivingDeathsRate'] > 0) & (countyHealthFactors['alcoholInvolvementDrivingDeathsRate'] <= 25.6), 'alcoholDrivingDeathsRateCategory'] = 1
countyHealthFactors.loc[countyHealthFactors['alcoholInvolvementDrivingDeathsRate'] > 25.6, 'alcoholDrivingDeathsRateCategory'] = 2

In [108]:
#let's do zero deaths, less than median, above median
countyHealthFactors['alcoholDrivingDeathsRateCategory'].value_counts()

2.0    1645
1.0    1318
0.0     153
Name: alcoholDrivingDeathsRateCategory, dtype: int64

In [109]:
countyHealthFactors['severeHousingProblemsRate'].value_counts()

14.285714    7
10.000000    6
9.090909     5
13.043478    5
8.333333     5
            ..
10.227937    1
12.638037    1
13.585746    1
11.593511    1
13.051312    1
Name: severeHousingProblemsRate, Length: 3041, dtype: int64

In [110]:
countyHealthFactors.loc[countyHealthFactors['severeHousingProblemsRate'] <= 12.6, 'housingProblemsRateCategory'] = 1
countyHealthFactors.loc[countyHealthFactors['severeHousingProblemsRate'] > 12.6, 'housingProblemsRateCategory'] = 2

In [111]:
countyHealthFactors['housingProblemsRateCategory'].value_counts()

1.0    1588
2.0    1555
Name: housingProblemsRateCategory, dtype: int64

In [112]:
countyHealthFactors['householdsWithBroadbandAccessRate'].value_counts()

79.900000    3
75.000000    3
55.800000    2
77.966102    2
72.100000    2
            ..
78.398876    1
75.551214    1
79.420019    1
85.394369    1
80.541481    1
Name: householdsWithBroadbandAccessRate, Length: 3130, dtype: int64

In [113]:
#below median
countyHealthFactors.loc[countyHealthFactors['householdsWithBroadbandAccessRate'] <= 81.7, 'broadbandAccessRateCategory'] = 1
#above median
countyHealthFactors.loc[countyHealthFactors['householdsWithBroadbandAccessRate'] > 81.7, 'broadbandAccessRateCategory'] = 2

In [114]:
countyHealthFactors['broadbandAccessRateCategory'].value_counts()

1.0    1572
2.0    1571
Name: broadbandAccessRateCategory, dtype: int64

In [115]:
#let's make sure the new variables are there and show up okay
countyHealthFactors.head()

,County,alcoholInvolvementDrivingDeaths,alcoholInvolvementDrivingDeathsRate,severeHousingProblemsRate,housingCostBurdenRate,housingOvercrowdingRate,Inadequate Facilities,driveAloneToWorkRate,householdsWithBroadbandAccess,householdsWithBroadbandAccessRate,alcoholDrivingDeathsRateCategory,housingProblemsRateCategory,broadbandAccessRateCategory
State,,,,,,,,,,,,,
Alabama,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Alabama,Autauga,18.0,32.1,14.4,12.6,1.1,1.6,86.4,18679.0,85.5,2.0,2.0,2.0
Alabama,Baldwin,57.0,32.2,12.2,10.6,1.3,0.6,81.4,76602.0,87.9,2.0,1.0,2.0
Alabama,Barbour,12.0,37.5,16.2,13.5,3.9,0.6,83.1,5872.0,64.6,2.0,2.0,1.0
Alabama,Bibb,6.0,21.4,11.3,8.0,1.2,2.2,87.0,5284.0,74.6,1.0,1.0,1.0

### Save to a new file

In [118]:
countyHealthFactors.to_csv(os.path.join(path, 'Achievement 6', '6.1 Cleaned Sourcing Data_deBeus.csv'))